title: Alberto Ramos
email: albertoramos@ufpr.br
baseurl: ""
url: "http://AlbertoRamos.github.io" # the base hostname & protocol for your site
github_username:  AlbertoRamos
markdown: kramdown
t:
  en:
    backto:  "back to"
    homeurl: "/home/"
    phd:     "Ph.D."
    master:  "Master"
    research: "Research"
    tcc:     "Term paper"
    intern:  "Internship"
  br:
    backto: "voltar para"
    homeurl:  "/"
    phd:     "Doutorado"
    master:  "Mestrado"
    pesquisa: "Pesquisa"
    tcc:     "TCC"
    intern:  "Iniciação Científica"
